//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsTasksCheck
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int id { get; set; }
        public string Task_name { get; set; }
        public Nullable<System.DateTime> Time_create { get; set; }
        public Nullable<bool> Complete { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
    }
}
